# Generated by Django 3.1.1 on 2020-09-08 18:02

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('Accounts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('Transactions', django.db.models.manager.Manager()),
            ],
        ),
    ]
